import { IProduct } from "./product.model";

export const produtos: IProduct[] = [
    { 'codProduto': 'alternador', 'imageURL': 'assets/img/alternador.png', 'nomeProduto': 'Alternador', 'descrisao': 'Os alternadores fazem parte do sistema elétrico que é acionado por uma correia ligada ao motor, deste modo, gera uma corrente alternada que é transformada em corrente contínua. Eles são essenciais e super importantes para converter a energia mecânica em energia elétrica. Ou seja, os alternadores servem para carregar a bateria e alimentar o sistema elétrico com o motor em funcionamento. Por isso que obter bons alternadores são essenciais para que eles possam garantir um bom funcionamento e alta qualidade as demandas do dia a dia.' },
    { 'codProduto': 'motor', 'imageURL': 'assets/img/partida-motor.png', 'nomeProduto': 'Motor de Partida', 'descrisao': 'O motor de arranque ou motor de partida é um motor elétrico com escovas que tem a função de transformar energia elétrica em energia mecânica. Sendo assim fica inoperante após realizar esta função no sistema de partida, permanecendo parado mesmo enquanto o motor do automóvel estiver em funcionamento.' },
    { 'codProduto': 'chave', 'imageURL': 'assets/img/seta.png', 'nomeProduto': 'Chave de Seta', 'descrisao': 'Toda a parte de sinalização, desde lanternas e setas a farol baixo e alto, além de acionar os limpadores de para-brisa em diversas velocidades, a chave de seta se tornou um dos itens mais usados do veículo, um instrumento essencial para condução, sinalização e segurança dos carros de hoje.' },
    { 'codProduto': 'ventilador', 'imageURL': 'assets/img/ventilador.png', 'nomeProduto': 'Eletro-ventilador', 'descrisao': 'Trata-se de um atuador do sistema de injeção eletrônica cuja a função é resfriar de forma forçada a água contida no radiador, para quando esta for liberada para o motor pela válvula termostática, possa arrefecer o motor e mante-lo na temperatura ideal de funcionamento. Para ativar o ventilador do radiador, a ECU leva em consideração várias informações' },
    { 'codProduto': 'lampada', 'imageURL': 'assets/img/lampada.PNG', 'nomeProduto': 'Lâmpadas Automotivas', 'descrisao': 'Seja para sinalizar ou iluminar o caminho à frente, as lâmpadas automotivas têm papel fundamental no trânsito. São itens essenciais para a segurança e foram evoluindo juntamente com os veículos para ampliar e trazer mais benefícios aos motoristas e passageiros. ' },
    { 'codProduto': 'revisao', 'imageURL': 'assets/img/revisao.png', 'nomeProduto': 'Revisão Automotiva', 'descrisao': 'A revisão automotiva é uma manutenção preventiva, que ajuda a garantir o melhor desempenho do seu carro. Também conhecida por revisão programada ou até revisão com preço fixo, deve ser feita periodicamente, respeitando principalmente os parâmetros orientados pelo fabricante.' }
];

